name: Build and deploy ASP.Net Core app to Azure Web App - number-api

on:
  push:
    branches:
      - main
    paths:
      - 'number-Minimal-API/**'  # Only trigger when this folder changes
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: number-Minimal-API

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: number-api-artifact
          path: number-Minimal-API/publish  # ✅ Absolute path from repo root

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: number-api-artifact
          path: ./publish  # ✅ Extract to ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D2D9CA2D0334AECB961BF53C6152795 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_46DFEEEA83524B75936395B8106644B5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_534FC030C6EC47749851B595AE065FC9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'number-api'
          slot-name: 'Production'
          package: ./publish  # ✅ Deploy from extracted artifact